name: restaurant_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  hidden_drawer_menu: ^3.0.1
  http: any
  provider:
  persistent_bottom_nav_bar: ^6.2.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  url_launcher:
  flutter_svg:


  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#f2f5f6"
  image: assets/images/logo2.png
  android: true
  ios: true
  web: true
  branding: null

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/maroua.png
    - assets/images/wiame.jpg
    - assets/images/flutter.png
    - assets/images/dart.png
    - assets/images/burger.jpg
    - assets/images/pizza.jpg
    - assets/images/tiramisu.jpg
    - assets/images/pizza_quatre_fromages.jpeg
    - assets/images/pizza_pepperoni.jpeg
    - assets/images/pizza_vegetarienne.jpeg
    - assets/images/pizza_fruits_mer.jpeg
    - assets/images/pizza_orientale.jpg
    - assets/images/pizza_royale.jpeg
    - assets/images/burger_cheese.jpeg
    - assets/images/burger_chicken.jpeg
    - assets/images/burger_fish.jpeg
    - assets/images/burger_vegetarien.jpg
    - assets/images/burger_bbq.jpeg
    - assets/images/burger_royal.jpeg
    - assets/images/tajine_poulet_olives.jpeg
    - assets/images/tajine_agneau_pruneaux.jpg
    - assets/images/tajine_boeuf_legumes.jpeg
    - assets/images/tajine_poisson.jpeg
    - assets/images/tajine_vegetarien.jpg
    - assets/images/couscous_royal.JPG
    - assets/images/couscous_agneau.jpeg
    - assets/images/couscous_poulet.jpeg
    - assets/images/couscous_vegetarien.jpg
    - assets/images/eau_sidi_ali.jpg
    - assets/images/coca_cola.jpg
    - assets/images/jus_orange.jpg
    - assets/images/limonade.jpg
    - assets/images/smoothie_fruits_rouges.JPG
    - assets/images/logo2.png
    - assets/images/lassi_mangue.jpeg
    - assets/images/baklava.jpeg
    - assets/images/creme_brulee.jpeg
    - assets/images/cafe_espresso.JPG
    - assets/images/the_menthe.jpeg
    - assets/images/tajine_kefta.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
